
version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_slug}}"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
    - dependency-type: direct
    - dependency-type: indirect
